name: "Install tx3 CLI tools"
description: "Installs tools to run the tx3 environment"

runs:
  using: "composite"
  steps:
    - name: Install tx3up
      run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/tx3-lang/up/releases/latest/download/tx3up-installer.sh | sh
      shell: bash

    - name: Install tools
      run: tx3up
      shell: bash

    - name: Set tx3 environment variables
      shell: bash
      run: |
        echo "$HOME/.tx3/default/bin:$PATH" >> $GITHUB_PATH
