[upstream]
block_production_interval = 5

[storage]
version = "v3"
path = "data"

[storage.wal]
backend = "in_memory"

[storage.state]
backend = "in_memory"

[storage.archive]
backend = "in_memory"

[storage.index]
backend = "in_memory"

[storage.mempool]
backend = "in_memory"

[genesis]
force_protocol = 9
byron_path = "./byron.json"
shelley_path = "./shelley.json"
alonzo_path = "./alonzo.json"
conway_path = "./conway.json"

[sync]
pull_batch_size = 100

[submit]

[serve.grpc]
listen_address = "[::]:5164"
permissive_cors = true

[serve.minibf]
listen_address = "[::]:3164"
permissive_cors = true

[serve.trp]
listen_address = "[::]:8164"
max_optimize_rounds = 10
permissive_cors = true

[chain]
type = "cardano"
magic = 2
is_testnet = true

[logging]
include_grpc = true
