[protocol]
scope = "txpipe"
name = "transfer"
version = "0.1.0"
description = "Test transfer protocol"
main = "main.tx3"
readme = "README.md"

[registry]
url = "http://localhost:3000"

[profiles.devnet]
chain = "CardanoDevnet"

[[profiles.devnet.wallets]]
name = "alice"
random_key = true
initial_balance = 1000000000000000000

[[profiles.devnet.wallets]]
name = "bob"
random_key = true
initial_balance = 1000000000000000000

[profiles.preview]
chain = "CardanoPreview"

[profiles.preprod]
chain = "CardanoPreprod"

[profiles.mainnet]
chain = "CardanoMainnet"

[[bindings]]
plugin = "typescript"
output_dir = "./gen/typescript"
